spring.application.name=internflow-api

spring.datasource.url=jdbc:postgresql://localhost:5433/internflow
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=internflow_user
spring.datasource.password=internflow_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 console is disabled because the application now uses PostgreSQL.
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console